#! /usr/bin/bash
. $HOME/.bashrc
cd $HOME/repos/soul
alias x=/opt/webstack/bin/python

function activate {
    /opt/webstack/bin/python $1.py 2>$HOME/cache/$1.err
}
	
activate filter
activate summarise
activate email
activate post

activate shtm
activate latest
activate archives
activate feed



POSTS=$HOME/cache/posts`/bin/date +%Y%m%d`
/bin/mkdir $POSTS
/bin/cp /uu/news/out.going/* $POSTS
